name: main

on:
  schedule:
    - cron: '10 * * * *'
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: bash main.sh
    - run: git config --local user.email "frogcat@users.noreply.github.com"
    - run: git config --local user.name "frogcat-bot"
    - run: git add dist
    - run: git commit -m "Update dist"
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
